# Book settings
title: The Astrobook
author: Jorge M.G.
logo: drawings/images/astro_logo.png
exclude_patterns: ["README.md", "CONTRIBUTING.md"]

latex:
  latex_documents:
    targetname: astrobook.tex
